from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from datetime import datetime
import os

class ReportGenerator:
    def generate_pdf_report(self, patient_name, age, exercise_data):
        """Generate a comprehensive PDF report"""
        
        os.makedirs('data/reports', exist_ok=True)
        filename = f'data/reports/report_{patient_name.replace(" ", "_")}_{datetime.now().strftime("%Y%m%d_%H%M%S")}.pdf'
        
        doc = SimpleDocTemplate(filename, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []
        
        # Title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#2E7D32'),
            spaceAfter=30,
            alignment=1
        )
        story.append(Paragraph("MediMotion Physiotherapy Report", title_style))
        story.append(Spacer(1, 12))
        
        # Patient Information
        story.append(Paragraph(f"<b>Patient Name:</b> {patient_name}", styles['Normal']))
        story.append(Paragraph(f"<b>Age:</b> {age}", styles['Normal']))
        story.append(Paragraph(f"<b>Report Date:</b> {datetime.now().strftime('%B %d, %Y')}", styles['Normal']))
        story.append(Spacer(1, 12))
        
        # Exercise Summary
        story.append(Paragraph("<b>Exercise Summary</b>", styles['Heading2']))
        story.append(Spacer(1, 6))
        
        for exercise in exercise_data:
            story.append(Paragraph(f"<b>Exercise:</b> {exercise['name'].replace('_', ' ').title()}", styles['Normal']))
            story.append(Paragraph(f"<b>Repetitions:</b> {exercise.get('reps', 0)}", styles['Normal']))
            story.append(Paragraph(f"<b>Performance Score:</b> {exercise.get('score', 0):.1f}%", styles['Normal']))
            story.append(Paragraph(f"<b>Feedback:</b> {exercise.get('feedback', '')}", styles['Normal']))
            
            # Angles table
            if 'angles' in exercise:
                angle_data = [[f"{joint.replace('_', ' ').title()}", f"{int(angle)}°"] 
                             for joint, angle in exercise['angles'].items()]
                
                angle_table = Table([['Joint', 'Angle']] + angle_data)
                angle_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, 0), 12),
                    ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                    ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                    ('GRID', (0, 0), (-1, -1), 1, colors.black)
                ]))
                story.append(angle_table)
            
            story.append(Spacer(1, 12))
        
        # Recommendations
        story.append(Paragraph("<b>Recommendations</b>", styles['Heading2']))
        story.append(Spacer(1, 6))
        
        recommendations = [
            "Perform exercises 2-3 times daily",
            "Maintain proper form and range of motion",
            "Rest between sets to avoid fatigue",
            "Consult your physiotherapist if you experience pain",
            "Track your progress regularly"
        ]
        
        for rec in recommendations:
            story.append(Paragraph(f"• {rec}", styles['Normal']))
        
        # Footer
        story.append(Spacer(1, 30))
        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=8,
            textColor=colors.grey,
            alignment=1
        )
        story.append(Paragraph("This report is generated by MediMotion AI Exercise Tracker", footer_style))
        
        doc.build(story)
        return filename