from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from datetime import datetime
import os

def generate_pdf_report(patient_name, age, exercise_name, performance_score, feedback_text):
    """Generate a PDF report for exercise performance"""
    
    os.makedirs("data/reports", exist_ok=True)
    filename = f"data/reports/report_{patient_name.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    
    doc = SimpleDocTemplate(filename, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []
    
    # Title
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#2E7D32'),
        spaceAfter=30,
        alignment=1
    )
    story.append(Paragraph("MediMotion Physiotherapy Report", title_style))
    story.append(Spacer(1, 12))
    
    # Patient Info
    story.append(Paragraph(f"<b>Patient Name:</b> {patient_name}", styles['Normal']))
    story.append(Paragraph(f"<b>Age:</b> {age}", styles['Normal']))
    story.append(Paragraph(f"<b>Exercise:</b> {exercise_name.replace('_', ' ').title()}", styles['Normal']))
    story.append(Paragraph(f"<b>Report Date:</b> {datetime.now().strftime('%B %d, %Y')}", styles['Normal']))
    story.append(Spacer(1, 12))
    
    # Performance Score
    story.append(Paragraph("<b>Performance Summary</b>", styles['Heading2']))
    story.append(Spacer(1, 6))
    story.append(Paragraph(f"<b>Performance Score:</b> {performance_score:.1f}%", styles['Normal']))
    story.append(Spacer(1, 6))
    
    # Feedback
    story.append(Paragraph("<b>AI Feedback</b>", styles['Heading2']))
    story.append(Spacer(1, 6))
    story.append(Paragraph(feedback_text, styles['Normal']))
    story.append(Spacer(1, 12))
    
    # Recommendations
    story.append(Paragraph("<b>Recommendations</b>", styles['Heading2']))
    story.append(Spacer(1, 6))
    recommendations = [
        "Perform exercises 2-3 times daily",
        "Maintain proper form and range of motion",
        "Rest between sets to avoid fatigue",
        "Consult your physiotherapist if you experience pain",
        "Track your progress regularly"
    ]
    
    for rec in recommendations:
        story.append(Paragraph(f"• {rec}", styles['Normal']))
    
    # Footer
    story.append(Spacer(1, 30))
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.grey,
        alignment=1
    )
    story.append(Paragraph("This report is generated by MediMotion AI Exercise Tracker", footer_style))
    
    doc.build(story)
    return filename
